### PR TITLE
Change the inertia values

### PR DESCRIPTION
**Pull request by FabianPG11**
What I noticed is that the inertia values of the URDF model were not right.
I created the model in Solidworks and got the inertia values. Replacing the previous inertia values with the new ones, I guess the simulation is working OK now!

### CODE REVIEW

**Review by kruusamae — APPROVED** [review]
tested with roslaunch `robotont_gazebo world_minimaze.launch model:=robotont_gazebo_basic` and keyboard teleop and seems to be working just fine

**Comment by kruusamae** [comment]
@mmaao @Veix123  travis ci is failing here because of the org->com issue. could you fix it or tell @FabianPG11 how to fix it. i think we wish to merge these new inertia values

**Comment by Veix123** [comment]
@FabianPG11  Can you change the build status in the Readme to https://travis-ci.com/robotont/robotont_description.svg?branch=melodic-devel I already fixed the github settings and it should build now.

**Comment by mmaao** [comment]
I changed the readme build status

**Comment by kruusamae** [comment]
coolio

**Pull request merged**
